USE [master]
GO

/****** Object:  Database [PowerBIResumeDemo]    Script Date: 10/20/2018 2:46:34 PM ******/
CREATE DATABASE [PowerBIResumeDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PowerBIResumeDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.RESUMEDATABASE\MSSQL\DATA\PowerBIResumeDemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PowerBIResumeDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.RESUMEDATABASE\MSSQL\DATA\PowerBIResumeDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PowerBIResumeDemo] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [PowerBIResumeDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PowerBIResumeDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PowerBIResumeDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PowerBIResumeDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PowerBIResumeDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PowerBIResumeDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET RECOVERY FULL 
GO

ALTER DATABASE [PowerBIResumeDemo] SET  MULTI_USER 
GO

ALTER DATABASE [PowerBIResumeDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PowerBIResumeDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PowerBIResumeDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PowerBIResumeDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PowerBIResumeDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PowerBIResumeDemo] SET QUERY_STORE = OFF
GO

USE [PowerBIResumeDemo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PowerBIResumeDemo] SET  READ_WRITE 
GO


